=== wasadmin/ewallet/CentralSwitchEJB/ejbModule/META-INF/BankInfoSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://bank.config.esolutions.co.zw"
	xmlns:tns="http://bank.config.esolutions.co.zw" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:annotation>
		<xs:documentation>Author : Blessing Bonde</xs:documentation>
	</xs:annotation>

	<element name="bankInfo" type="tns:BankInfo"></element>

	<complexType name="BankInfo">
		<sequence>
			<element name="requestQueueName" type="string"></element>
			<element name="replyQueueName" type="string"></element>
			<element name="bankName" type="string"></element>
			<element name="zswCode" type="string"></element>
			<element name="zesaPayCode" type="int"></element>
			<element name="zesaPayBranch" type="int"></element>
			<element name="bankId" type="string"></element>
			<element name="online" type="boolean"></element>
			<element name="signature" type="string"></element>
			<element name="applySignature" type="boolean"></element>
			<element name="smsCode" type="string"></element>
			<element name="ussdCode" type="string"></element>
			<element name="applyVendorSignature" type="boolean"></element>
			<element name="serviceId" type="string"></element>
			<element name="serviceProviderId" type="string"></element>
			<element name="alternateBankId" type="string"></element>
		</sequence>
	</complexType>
</schema>

=== wasadmin/ewallet/CentralSwitchEJB/ejbModule/META-INF/bank.6.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:bankInfo xmlns:tns="http://bank.config.esolutions.co.zw" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bank.config.esolutions.co.zw BankInfoSchema.xsd ">
  <tns:requestQueueName>ZB.IN.QUEUE</tns:requestQueueName>
  <tns:replyQueueName>BANKS.REPLY.QUEUE</tns:replyQueueName>
  <tns:bankName>ZB Bank</tns:bankName>
  <tns:zswCode>589003</tns:zswCode>
  <tns:zesaPayCode>14</tns:zesaPayCode>
  <tns:zesaPayBranch>4131</tns:zesaPayBranch>
  <tns:bankId>589003</tns:bankId>
  <tns:online>true</tns:online>
  <tns:signature>ZB e-Wallet</tns:signature>
  <tns:applySignature>true</tns:applySignature>
  <tns:smsCode>6</tns:smsCode>
  <tns:ussdCode>600</tns:ussdCode>
  <tns:applyVendorSignature>true</tns:applyVendorSignature>
  <tns:serviceId>67</tns:serviceId>
  <tns:serviceProviderId>tns:serviceProviderId</tns:serviceProviderId>
  <tns:alternateBankId>1299679872970688</tns:alternateBankId>
</tns:bankInfo>

=== wasadmin/ewallet/CentralSwitchEJB/ejbModule/META-INF/bank.7.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:bankInfo xmlns:tns="http://bank.config.esolutions.co.zw" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bank.config.esolutions.co.zw BankInfoSchema.xsd ">
  <tns:requestQueueName>ZABG.IN.QUEUE</tns:requestQueueName>
  <tns:replyQueueName>BANKS.REPLY.QUEUE</tns:replyQueueName>
  <tns:bankName>ZABG</tns:bankName>
  <tns:zswCode>tns:zswCode</tns:zswCode>
  <tns:zesaPayCode>0</tns:zesaPayCode>
  <tns:zesaPayBranch>0</tns:zesaPayBranch>
  <tns:bankId>tns:bankId</tns:bankId>
  <tns:online>true</tns:online>
  <tns:signature>tns:signature</tns:signature>
  <tns:applySignature>true</tns:applySignature>
  <tns:smsCode>tns:smsCode</tns:smsCode>
  <tns:ussdCode>tns:ussdCode</tns:ussdCode>
  <tns:applyVendorSignature>true</tns:applyVendorSignature>
  <tns:serviceId>tns:serviceId</tns:serviceId>
  <tns:serviceProviderId>tns:serviceProviderId</tns:serviceProviderId>
  <tns:alternateBankId>tns:alternateBankId</tns:alternateBankId>
</tns:bankInfo>
