=== wasadmin/ewallet/CentralSwitchEJB/ejbModule/META-INF/MerchantInfoSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://merchant.config.esolutions.co.zw"
	xmlns:tns="http://merchant.config.esolutions.co.zw" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:annotation>
		<xs:documentation>Author : Blessing Bonde</xs:documentation>
	</xs:annotation>

	<element name="merchantInfo" type="tns:MerchantInfo"></element>

	<complexType name="MerchantInfo">
		<sequence>
			<element name="requestQueueName" type="string"></element>
			<element name="replyQueueName" type="string"></element>
			<element name="merchantName" type="string"></element>
			<element name="enableAccountValidation" type="boolean"></element>
			<element name="enableStraightThrough" type="boolean"></element>
			<element name="enableNotification" type="boolean"></element>
			<element name="reversalCutOffTime" type="time"></element>
			<element name="transactionCuttoffTime" type="time"></element>
		</sequence>
	</complexType>
</schema>

=== wasadmin/ewallet/CentralSwitchEJB/ejbModule/META-INF/zetdc.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:merchantInfo xmlns:tns="http://merchant.config.esolutions.co.zw" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://merchant.config.esolutions.co.zw MerchantInfoSchema.xsd ">
  <tns:requestQueueName>tns:requestQueueName</tns:requestQueueName>
  <tns:replyQueueName>tns:replyQueueName</tns:replyQueueName>
  <tns:merchantName>tns:merchantName</tns:merchantName>
  <tns:enableAccountValidation>true</tns:enableAccountValidation>
  <tns:enableStraightThrough>true</tns:enableStraightThrough>
  <tns:enableNotification>true</tns:enableNotification>
  <tns:reversalCutOffTime>12:00:00</tns:reversalCutOffTime>
  <tns:transactionCuttoffTime>12:00:00</tns:transactionCuttoffTime>
</tns:merchantInfo>
